[package]
name = "patternsleuth"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "scan"
harness = false

[dependencies]
anyhow = "1.0.71"
colored = "2.0.0"
itertools = "0.10.5"
object = "0.31.1"
prettytable-rs = "0.10.0"
rayon = "1.7.0"
regex = "1.8.1"
strum = {version = "0.24.1", features = ["strum_macros", "derive"]}

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"
