[package]
name = "patternsleuth"
repository.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
patternsleuth_scanner = { path = "../patternsleuth_scanner" }
anyhow = { workspace = true }
byteorder = { workspace = true }
itertools = { workspace = true }
memchr = { workspace = true }
msvc-demangler = { workspace = true }
object = { workspace = true }
pdb = { workspace = true }
rayon = { workspace = true }
strum = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.149", optional = true }

[features]
process = ["dep:libc"]
